name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --detection-depth=10 --all-projects
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Prepare files to archive
        run: |
          mkdir -p root/backup/
          touch root/backup/file
          touch root/file
        shell: bash

      - name: Create zip
        uses: ihiroky/archive-action@v1
        with:
          root_dir: root
          file_path: backup.zip
          verbose: true
      - name: Extract zip
        uses: ihiroky/extract-action@main
        with:
          file_path: backup.zip
          extract_dir: extract/zip
      - run: test -f extract/zip/backup/file -a -f extract/zip/file
